version: '3'

services:
  ftp:
    image: delfer/alpine-ftp-server
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      USERS: "one|12345"
      ADDRESS: ftp.site.domain
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
